#!/bin/bash
DIR="$(dirname "$(readlink -f "$0")")"
source "${DIR}/clang-wrapper.cfg"
source "${DIR}/clang-wrapper-functions.sh"
# echo "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
run_compilation "clang" "$@"

