#!/bin/bash
DIR="$(dirname "$(readlink -f "$0")")"
source "${DIR}/clang-wrapper.cfg"
source "${DIR}/clang-wrapper-functions.sh"
# echo "########################### clang++ wrapper called"
# echo "clang++ wrapper args: " "$@"
run_compilation "clang++" "$@"

